<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class BarangSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('barangs')->insert([
            [
                'nama' => 'iPhone 11 Putih',
                'tipe_id' => 1, // Hilang
                'kategori_id' => 4, // Smartphone
                'pelapor_id' => 1,
                'waktu' => Carbon::now()->subMinutes(20),
                'lokasi' => 'Nakoa Cafe Suhat',
                'kontak' => '082111223344',
                'deskripsi' => 'iPhone 11 warna ungu dengan casing bening. Terakhir terlihat di meja pojok dekat jendela.',
                'foto' => 'https://images.tokopedia.net/img/cache/700/VqbcmM/2024/1/5/aecdaea5-bf4d-4213-bea1-516253e8753f.jpg',
                'status_id' => 2, // Belum Ditemukan
            ],
            [
                'nama' => 'Dompet Eiger Coklat',
                'tipe_id' => 2, // Temuan
                'kategori_id' => 1, // Dompet
                'pelapor_id' => 1,
                'waktu' => Carbon::now()->subMinutes(25),
                'lokasi' => 'Kantin CL UB',
                'kontak' => '082222334455',
                'deskripsi' => 'Dompet Eiger berwarna coklat tua berisi KTP dan KTM atas nama Rudi.',
                'foto' => 'https://filebroker-cdn.lazada.co.id/kf/S322c7f8d27ba42b7bace2cbfdb156ff7G.jpg',
                'status_id' => 1, // Belum Dikembalikan
            ],
            [
                'nama' => 'Headset Fantech',
                'tipe_id' => 1, // Hilang
                'kategori_id' => 5, // Elektronik
                'pelapor_id' => 1,
                'waktu' => Carbon::now()->subMinutes(30),
                'lokasi' => 'Game Corner FILKOM',
                'kontak' => '081234567890',
                'deskripsi' => 'Headset gaming merk Fantech warna hitam dengan kabel agak rusak.',
                'foto' => 'https://media.karousell.com/media/photos/products/2023/1/12/fantech_chief_ii_hg20_rgb_gami_1673484758_26d7fc27_progressive.jpg',
                'status_id' => 2, // Belum Ditemukan
            ],
            [
                'nama' => 'Mouse Logitech G Pro',
                'tipe_id' => 2, // Temuan
                'kategori_id' => 5, // Elektronik
                'pelapor_id' => 1,
                'waktu' => Carbon::now()->subMinutes(35),
                'lokasi' => 'Lab G1.3 FILKOM',
                'kontak' => '083344556677',
                'deskripsi' => 'Mouse putih Logitech G Pro Wireless tertinggal di lab saat praktikum.',
                'foto' => 'https://down-id.img.susercontent.com/file/id-11134207-7rasi-m57cdwnkwxsm40',
                'status_id' => 1, // Belum Dikembalikan
            ],
            [
                'nama' => 'Tumbler Corkcicle',
                'tipe_id' => 1, // Hilang
                'kategori_id' => 6, // Botol Minum
                'pelapor_id' => 1,
                'waktu' => Carbon::now()->subMinutes(40),
                'lokasi' => 'AADK Tlogomas',
                'kontak' => '088899001122',
                'deskripsi' => 'Tumbler pink muda merk Corkcicle tertinggal di atas meja.',
                'foto' => 'https://img.lazcdn.com/g/p/0161eb2936426a336a59eee0357364d9.jpg_360x360q80.jpg_.webp',
                'status_id' => 2, // Belum Ditemukan
            ],
            [
                'nama' => 'Jam Tangan Tissot',
                'tipe_id' => 2, // Temuan
                'kategori_id' => 3, // Aksesoris
                'pelapor_id' => 1,
                'waktu' => Carbon::now()->subMinutes(45),
                'lokasi' => 'Masjid Sabilillah',
                'kontak' => '089912345678',
                'deskripsi' => 'Jam tangan Tissot hitam dengan tali kulit. Terakhir digunakan saat salat Maghrib.',
                'foto' => 'https://down-id.img.susercontent.com/file/id-11134207-7r98o-lzzw1xldpd6w8d',
                'status_id' => 1, // Belum Dikembalikan
            ],
            [
                'nama' => 'Dompet Charles & Keith',
                'tipe_id' => 1, // Hilang
                'kategori_id' => 1, // Dompet
                'pelapor_id' => 1,
                'waktu' => Carbon::now()->subMinutes(80),
                'lokasi' => 'Transmart Malang',
                'kontak' => '081234567890',
                'deskripsi' => 'Dompet wanita Charles & Keith warna elegan, tertinggal saat nongkrong.',
                'foto' => 'https://media.karousell.com/media/photos/products/2025/5/22/dompet_charles__keith_1747902591_aaae8bc1_progressive_thumbnail.jpg',
                'status_id' => 2,
            ],
            [
                'nama' => 'Dompet pria Bally',
                'tipe_id' => 2, // Temuan
                'kategori_id' => 1,
                'pelapor_id' => 1,
                'waktu' => Carbon::now()->subMinutes(105),
                'lokasi' => 'Pasar Klojen Malang',
                'kontak' => '081234567890',
                'deskripsi' => 'Dompet pria merk Bally ditemukan di parkiran cafe, masih berisi kartu.',
                'foto' => 'https://media.karousell.com/media/photos/products/2025/5/22/dompet_pria_bally_1747895058_db7933b9_progressive_thumbnail.jpg',
                'status_id' => 1,
            ],
            [
                'nama' => 'Dompet Pria Louis Vuitton kulit asli',
                'tipe_id' => 1,
                'kategori_id' => 1,
                'pelapor_id' => 1,
                'waktu' => Carbon::now()->subMinutes(130),
                'lokasi' => 'Swalayan Sardo',
                'kontak' => '081234567890',
                'deskripsi' => 'Dompet LV pria, kulit asli, kemungkinan tertinggal saat isi BBM.',
                'foto' => 'https://media.karousell.com/media/photos/products/2025/5/20/dompet_pria_louis_vuitton_kuli_1747713029_5bc06823_progressive_thumbnail.jpg',
                'status_id' => 2,
            ],
            [
                'nama' => 'Dompet panjang Lucky Duck',
                'tipe_id' => 2,
                'kategori_id' => 1,
                'pelapor_id' => 1,
                'waktu' => Carbon::now()->subMinutes(160),
                'lokasi' => 'CW Coffee Tlogomas',
                'kontak' => '081234567890',
                'deskripsi' => 'Dompet panjang merk Lucky Duck ditemukan di taman kota.',
                'foto' => 'https://media.karousell.com/media/photos/products/2025/5/22/dompet_panjang_lucky_duck_1747898640_4c37bf03_progressive_thumbnail.jpg',
                'status_id' => 1,
            ],
            [
                'nama' => 'Dompet motif',
                'tipe_id' => 1,
                'kategori_id' => 1,
                'pelapor_id' => 1,
                'waktu' => Carbon::now()->subMinutes(190),
                'lokasi' => 'Depot Tanjung Api',
                'kontak' => '081234567890',
                'deskripsi' => 'Dompet dengan motif bunga-bunga, kemungkinan jatuh di angkot.',
                'foto' => 'https://media.karousell.com/media/photos/products/2025/5/21/dompet_motif_1747842578_35ef4357_progressive_thumbnail',
                'status_id' => 2,
            ],
            [
                'nama' => 'Gantungan Kunci Motor',
                'tipe_id' => 2,
                'kategori_id' => 2, // Kunci
                'pelapor_id' => 1,
                'waktu' => Carbon::now()->subMinutes(120),
                'lokasi' => 'Taman Merjosari',
                'kontak' => '081234567890',
                'deskripsi' => 'Gantungan kunci motor bentuk lucu ditemukan di trotoar Jalan Soekarno Hatta.',
                'foto' => 'https://media.karousell.com/media/photos/products/2023/6/18/gantungan_kunci_motor_mobil_ku_1687050041_2d4a691f_progressive_thumbnail',
                'status_id' => 1,
            ],
            [
                'nama' => 'Kunci motor keyles',
                'tipe_id' => 1,
                'kategori_id' => 2,
                'pelapor_id' => 1,
                'waktu' => Carbon::now()->subMinutes(80),
                'lokasi' => 'Masjid Agung Malanng',
                'kontak' => '081234567890',
                'deskripsi' => 'Kunci motor keyles hilang, terakhir digunakan di parkiran kampus.',
                'foto' => 'https://media.karousell.com/media/photos/products/2025/5/16/kunci_motor_keyles_masih_baru__1747360788_d7925394_progressive_thumbnail.jpg',
                'status_id' => 2,
            ],
            [
                'nama' => 'Gantungan Kunci Motor BMW',
                'tipe_id' => 2,
                'kategori_id' => 2,
                'pelapor_id' => 1,
                'waktu' => Carbon::now()->subMinutes(115),
                'lokasi' => 'Apartemen Begawan',
                'kontak' => '081234567890',
                'deskripsi' => 'Gantungan kunci BMW berbahan kulit ditemukan dekat ATM center.',
                'foto' => 'https://media.karousell.com/media/photos/products/2023/12/15/gantungan_kunci_motor_bmw_keyc_1702630109_56e7f347_progressive_thumbnail',
                'status_id' => 1,
            ],
            [
                'nama' => 'Set Kunci Motor Honda Vario 125',
                'tipe_id' => 1,
                'kategori_id' => 2,
                'pelapor_id' => 1,
                'waktu' => Carbon::now()->subMinutes(100),
                'lokasi' => 'Malang Town Square',
                'kontak' => '081234567890',
                'deskripsi' => 'Set kunci motor Vario 125 hilang saat pulang kerja.',
                'foto' => 'https://media.karousell.com/media/photos/products/2024/11/3/set_kunci_motor_honda_vario_12_1730622058_b4b2c9f3_progressive_thumbnail.jpg',
                'status_id' => 2,
            ],
            [
                'nama' => 'Kunci Sepeda Onthel',
                'tipe_id' => 2,
                'kategori_id' => 2,
                'pelapor_id' => 1,
                'waktu' => Carbon::now()->subMinutes(130),
                'lokasi' => 'Depot Kayutangan',
                'kontak' => '081234567890',
                'deskripsi' => 'Kunci sepeda Onthel jadul ditemukan di belakang kampus.',
                'foto' => 'https://media.karousell.com/media/photos/products/2024/9/20/kunci_sepeda_onthel_jadul_yws__1726799923_1b60b0cd_progressive_thumbnail',
                'status_id' => 1,
            ],
            [
                'nama' => 'Kunci Mobil HRV',
                'tipe_id' => 1,
                'kategori_id' => 2,
                'pelapor_id' => 1,
                'waktu' => Carbon::now()->subMinutes(70),
                'lokasi' => 'Mall Dinoyo City',
                'kontak' => '081234567890',
                'deskripsi' => 'Kunci mobil Honda HRV hilang, kemungkinan tertinggal di tempat parkir ruko.',
                'foto' => 'https://media.karousell.com/media/photos/products/2024/12/26/kunci_mobil_hrv_1735206474_8e9e2f33_progressive_thumbnail.jpg',
                'status_id' => 2,
            ],
            [
                'nama' => 'Jam Tangan Alexander Cristie',
                'tipe_id' => 1, // Hilang
                'kategori_id' => 3, // Aksesoris
                'pelapor_id' => 1,
                'waktu' => Carbon::now()->subMinutes(105),
                'lokasi' => 'Alun-Alun Kota Malang',
                'kontak' => '081234567890',
                'deskripsi' => 'Jam tangan Alexander Cristi warna silver, hilang saat jalan-jalan di Alun-Alun.',
                'foto' => 'https://media.karousell.com/media/photos/products/2025/3/4/jam_tangan_alexander_cristie_1741058345_b569a0da_progressive_thumbnail.jpg',
                'status_id' => 2,
            ],
            [
                'nama' => 'Jam tangan Swatch',
                'tipe_id' => 2, // Temuan
                'kategori_id' => 3,
                'pelapor_id' => 1,
                'waktu' => Carbon::now()->subMinutes(125),
                'lokasi' => 'Stasiun Kota Baru Malang',
                'kontak' => '081234567890',
                'deskripsi' => 'Jam tangan Swatch warna hitam ditemukan di ruang tunggu stasiun.',
                'foto' => 'https://media.karousell.com/media/photos/products/2025/1/16/jam_tangan_swatch_1737041531_582af0ff_progressive_thumbnail.jpg',
                'status_id' => 1,
            ],
            [
                'nama' => 'Kalung Mutiara',
                'tipe_id' => 1,
                'kategori_id' => 3,
                'pelapor_id' => 1,
                'waktu' => Carbon::now()->subMinutes(135),
                'lokasi' => 'Matos Malang',
                'kontak' => '081234567890',
                'deskripsi' => 'Kalung mutiara putih, terakhir terlihat di area food court Matos.',
                'foto' => 'https://media.karousell.com/media/photos/products/2021/7/31/kalung_mutiara_1627745457_1d0ce319_progressive_thumbnail.jpg',
                'status_id' => 2,
            ],
            [
                'nama' => 'Gelang Bangle Titanium',
                'tipe_id' => 2,
                'kategori_id' => 3,
                'pelapor_id' => 1,
                'waktu' => Carbon::now()->subMinutes(150),
                'lokasi' => 'Kafe Kajoetangan',
                'kontak' => '081234567890',
                'deskripsi' => 'Ditemukan gelang bangle titanium perak di bawah kursi kafe.',
                'foto' => 'https://media.karousell.com/media/photos/products/2025/4/15/gelang_bangle_titanium_1744722557_2faae0c8_progressive_thumbnail.jpg',
                'status_id' => 1,
            ],
            [
                'nama' => 'Cincin Moissanite',
                'tipe_id' => 1,
                'kategori_id' => 3,
                'pelapor_id' => 1,
                'waktu' => Carbon::now()->subMinutes(125),
                'lokasi' => 'Malang Town Square',
                'kontak' => '081234567890',
                'deskripsi' => 'Cincin Moissanite dengan batu kecil hilang saat berbelanja.',
                'foto' => 'https://media.karousell.com/media/photos/products/2025/4/15/cincin_moissanite_1744728643_19f39e99_progressive_thumbnail.jpg',
                'status_id' => 2,
            ],
            [
                'nama' => 'Jam Police Skull',
                'tipe_id' => 2,
                'kategori_id' => 3,
                'pelapor_id' => 1,
                'waktu' => Carbon::now()->subMinutes(145),
                'lokasi' => 'GOR Ken Arok',
                'kontak' => '081234567890',
                'deskripsi' => 'Jam tangan Police Skull ditemukan di toilet GOR.',
                'foto' => 'https://media.karousell.com/media/photos/products/2024/12/11/jam_police_skull_1733902296_2c3ee4b8_progressive_thumbnail.jpg',
                'status_id' => 1,
            ],
            [
                'nama' => 'iPhone 13 Promax',
                'tipe_id' => 1,
                'kategori_id' => 4, // Smartphone
                'pelapor_id' => 1,
                'waktu' => Carbon::now()->subMinutes(75),
                'lokasi' => 'Kampus UB FISIP',
                'kontak' => '081234567890',
                'deskripsi' => 'iPhone 13 Promax hilang saat praktikum, terakhir digunakan di ruang kelas.',
                'foto' => 'https://media.karousell.com/media/photos/products/2025/5/8/iphone_13_promax_ibox_1746701139_2615f6fe_progressive_thumbnail.jpg',
                'status_id' => 2,
            ],
            [
                'nama' => 'iPhone X 256GB Mulus',
                'tipe_id' => 2,
                'kategori_id' => 4,
                'pelapor_id' => 1,
                'waktu' => Carbon::now()->subMinutes(105),
                'lokasi' => 'Kost Jalan Sumbersari',
                'kontak' => '081234567890',
                'deskripsi' => 'Ditemukan iPhone X 256GB dalam kondisi mulus tanpa casing.',
                'foto' => 'https://media.karousell.com/media/photos/products/2024/10/20/iphone_x_256gb_mulus_ibox_1729403218_c6d027f8_progressive_thumbnail.jpg',
                'status_id' => 1,
            ],
            [
                'nama' => 'Oppo A57',
                'tipe_id' => 1,
                'kategori_id' => 4,
                'pelapor_id' => 1,
                'waktu' => Carbon::now()->subMinutes(135),
                'lokasi' => 'Terminal Arjosari',
                'kontak' => '081234567890',
                'deskripsi' => 'HP Oppo A57 warna hijau hilang saat naik angkot jurusan Landungsari.',
                'foto' => 'https://media.karousell.com/media/photos/products/2024/6/19/oppo_a57_1718817043_c9c7fd89_progressive_thumbnail.jpg',
                'status_id' => 2,
            ],
            [
                'nama' => 'Samsung Galaxy S22 Plus',
                'tipe_id' => 2,
                'kategori_id' => 4,
                'pelapor_id' => 1,
                'waktu' => Carbon::now()->subMinutes(150),
                'lokasi' => 'Museum Brawijaya',
                'kontak' => '081234567890',
                'deskripsi' => 'Samsung Galaxy S22 Plus ditemukan di kursi taman luar museum.',
                'foto' => 'https://media.karousell.com/media/photos/products/2025/3/8/samsung_galaxy_s_22_plus_1741404073_acdc6491_progressive_thumbnail.jpg',
                'status_id' => 1,
            ],
            [
                'nama' => 'Case Samsung A55 5G',
                'tipe_id' => 1,
                'kategori_id' => 4,
                'pelapor_id' => 1,
                'waktu' => Carbon::now()->subMinutes(185),
                'lokasi' => 'Indomaret Veteran Malang',
                'kontak' => '081234567890',
                'deskripsi' => 'Case Samsung A55 5G warna hitam dengan aksen emas hilang di meja kasir.',
                'foto' => 'https://media.karousell.com/media/photos/products/2025/4/29/case_samsung_a55_5g_1745923763_37120de1_progressive_thumbnail.jpg',
                'status_id' => 2,
            ],
            [
                'nama' => 'iPhone 13 512GB Blue',
                'tipe_id' => 2,
                'kategori_id' => 4,
                'pelapor_id' => 1,
                'waktu' => Carbon::now()->subMinutes(205),
                'lokasi' => 'Perpustakaan UM Malang',
                'kontak' => '081234567890',
                'deskripsi' => 'iPhone 13 512GB biru ditemukan di rak buku lantai 3, kondisi menyala.',
                'foto' => 'https://media.karousell.com/media/photos/products/2025/5/22/iphone_13_512gb_blue_garansi_e_1747903506_e9ae5def_progressive_thumbnail.jpg',
                'status_id' => 1,
            ],
            [
                'nama' => 'Car Charger USB',
                'tipe_id' => 1,
                'kategori_id' => 5,
                'pelapor_id' => 1,
                'waktu' => Carbon::now()->subMinutes(100),
                'lokasi' => 'Parkiran Cyber Mall Malang',
                'kontak' => '081234567890',
                'deskripsi' => 'Car charger USB 2 port hilang di mobil setelah parkir.',
                'foto' => 'https://media.karousell.com/media/photos/products/2025/3/18/car_charger_usb_2_port_usb_3_p_1742274131_cec1e93e_progressive_thumbnail.jpg',
                'status_id' => 2,
            ],
            [
                'nama' => 'Charger iPhone 20 Watt',
                'tipe_id' => 2,
                'kategori_id' => 5,
                'pelapor_id' => 1,
                'waktu' => Carbon::now()->subMinutes(65),
                'lokasi' => 'Pesen Kopi Plus Dinoyo',
                'kontak' => '081234567890',
                'deskripsi' => 'Charger iPhone 20 Watt putih ditemukan di ruang baca.',
                'foto' => 'https://media.karousell.com/media/photos/products/2025/5/21/charger_iphone_20_watt_1747802174_ec26d95e_progressive_thumbnail.jpg',
                'status_id' => 1,
            ],
            [
                'nama' => 'Baseus Fast Charger Hitam',
                'tipe_id' => 1,
                'kategori_id' => 5,
                'pelapor_id' => 1,
                'waktu' => Carbon::now()->subMinutes(145),
                'lokasi' => 'Kantin FEB UB',
                'kontak' => '081234567890',
                'deskripsi' => 'Charger Baseus Fast Hitam hilang setelah digunakan.',
                'foto' => 'https://media.karousell.com/media/photos/products/2025/5/18/baseus_fast_charger_hitam_ipho_1747573280_97e40b9b_progressive_thumbnail.jpg',
                'status_id' => 2,
            ],
            [
                'nama' => 'Adaptor Charger Laptop ASUS',
                'tipe_id' => 2,
                'kategori_id' => 5,
                'pelapor_id' => 1,
                'waktu' => Carbon::now()->subMinutes(175),
                'lokasi' => 'Laboratorium Komputer UB',
                'kontak' => '081234567890',
                'deskripsi' => 'Adaptor charger laptop ASUS warna hitam ditemukan di bawah meja.',
                'foto' => 'https://media.karousell.com/media/photos/products/2025/5/12/adaptor_charger_laptop_asus_1747059068_250becd2_progressive_thumbnail.jpg',
                'status_id' => 1,
            ],
            [
                'nama' => 'Headset Original Vivo',
                'tipe_id' => 1,
                'kategori_id' => 5,
                'pelapor_id' => 1,
                'waktu' => Carbon::now()->subMinutes(value: 235),
                'lokasi' => 'Bioskop Transmart MX',
                'kontak' => '081234567890',
                'deskripsi' => 'Headset original Vivo hilang di ruang teater.',
                'foto' => 'https://media.karousell.com/media/photos/products/2024/10/3/headset_original_vivo_type_c_c_1727944283_32711aeb_progressive_thumbnail.jpg',
                'status_id' => 2,
            ],
            [
                'nama' => 'Mouse Fantech Raigor II',
                'tipe_id' => 2,
                'kategori_id' => 5,
                'pelapor_id' => 1,
                'waktu' => Carbon::now()->subMinutes(80),
                'lokasi' => 'Roketto Cafe',
                'kontak' => '081234567890',
                'deskripsi' => 'Mouse Fantech Raigor II ditemukan di meja nomor 3.',
                'foto' => 'https://media.karousell.com/media/photos/products/2025/5/21/mouse_fantech_raigor_ii_1747841468_ffd60dff_progressive_thumbnail.jpg',
                'status_id' => 1,
            ],
            [
                'nama' => 'Botol Plastik Hijau',
                'tipe_id' => 1,
                'kategori_id' => 6,
                'pelapor_id' => 1,
                'waktu' => Carbon::now()->subMinutes(85),
                'lokasi' => 'Lapangan Rampal',
                'kontak' => '081234567890',
                'deskripsi' => 'Botol minum plastik transparan hilang saat olahraga.',
                'foto' => 'https://media.karousell.com/media/photos/products/2025/5/21/botol_minum_1747838691_e79c93b0_progressive_thumbnail.jpg',
                'status_id' => 2,
            ],
            [
                'nama' => 'Botol Minum BNI Hijau',
                'tipe_id' => 2,
                'kategori_id' => 6,
                'pelapor_id' => 1,
                'waktu' => Carbon::now()->subMinutes(165),
                'lokasi' => 'Ruang Guru SMAN 3 Malang',
                'kontak' => '081234567890',
                'deskripsi' => 'Thermos minum ditemukan di meja guru, masih hangat.',
                'foto' => 'https://media.karousell.com/media/photos/products/2025/5/21/botol_tempat_minum_thermos_ter_1747833099_6be12a6f_progressive_thumbnail.jpg',
                'status_id' => 1,
            ],
            [
                'nama' => 'Botol Minum 500ml',
                'tipe_id' => 1,
                'kategori_id' => 6,
                'pelapor_id' => 1,
                'waktu' => Carbon::now()->subMinutes(70),
                'lokasi' => 'Pasar Oro-Oro Dowo',
                'kontak' => '081234567890',
                'deskripsi' => 'Botol minum 500ml hilang setelah belanja di pasar.',
                'foto' => 'https://media.karousell.com/media/photos/products/2025/5/21/new_botol_minum_500ml_1747855752_6ade518a_progressive_thumbnail.jpg',
                'status_id' => 2,
            ],
            [
                'nama' => 'Botol Tupperware',
                'tipe_id' => 2,
                'kategori_id' => 6,
                'pelapor_id' => 1,
                'waktu' => Carbon::now()->subMinutes(65),
                'lokasi' => 'Warung Mekar Jaya',
                'kontak' => '081234567890',
                'deskripsi' => 'Ditemukan botol Tupperware 350ml warna biru di tempat wudhu.',
                'foto' => 'https://media.karousell.com/media/photos/products/2025/5/21/botol_minum_tupperware_350375m_1747810858_1878a72b_progressive_thumbnail.jpg',
                'status_id' => 1,
            ],
            [
                'nama' => 'Tumbler Tyeso Ori',
                'tipe_id' => 1,
                'kategori_id' => 6,
                'pelapor_id' => 1,
                'waktu' => Carbon::now()->subMinutes(230),
                'lokasi' => 'Perpustakaan UB',
                'kontak' => '081234567890',
                'deskripsi' => 'Tumbler Tyeso hilang, tertinggal di meja baca lantai 1.',
                'foto' => 'https://media.karousell.com/media/photos/products/2025/5/19/tumbler_tyeso_ori__botol_minum_1747658504_29ed2f5a_progressive_thumbnail.jpg',
                'status_id' => 2,
            ],
            [
                'nama' => 'Eplas Botol Minum 500 ml',
                'tipe_id' => 2,
                'kategori_id' => 6,
                'pelapor_id' => 1,
                'waktu' => Carbon::now()->subMinutes(245),
                'lokasi' => 'Lapangan Rektorat UB',
                'kontak' => '081234567890',
                'deskripsi' => 'Botol Eplas 500ml ditemukan setelah acara senam pagi.',
                'foto' => 'https://media.karousell.com/media/photos/products/2025/5/12/_nett__eplas_botol_minum_500_m_1747025985_7ed89fdc_progressive_thumbnail.jpg',
                'status_id' => 1,
            ],
            [
                'nama' => 'Pensil Warna Faber Castell',
                'tipe_id' => 1,
                'kategori_id' => 6,
                'pelapor_id' => 1,
                'waktu' => Carbon::now()->subMinutes(80),
                'lokasi' => 'Ruang Gambar FT UM',
                'kontak' => '081234567890',
                'deskripsi' => 'Pensil warna lengkap hilang saat praktik seni rupa.',
                'foto' => 'https://media.karousell.com/media/photos/products/2025/5/16/pensil_warna_faber_castell_1747395518_dff713e2_progressive_thumbnail.jpg',
                'status_id' => 2,
            ],
            [
                'nama' => 'Pensil Faber-Castell',
                'tipe_id' => 1,
                'kategori_id' => 6,
                'pelapor_id' => 1,
                'waktu' => Carbon::now()->subMinutes(115),
                'lokasi' => 'Perpustakaan Pusat UM',
                'kontak' => '081234567891',
                'deskripsi' => 'Pensil Faber-Castell tertinggal saat belajar.',
                'foto' => 'https://media.karousell.com/media/photos/products/2025/5/15/pensil_fabercastell_1747312468_58e72733_progressive_thumbnail.jpg',
                'status_id' => 2,
            ],
            [
                'nama' => 'Buku Novel Looking For Alaska',
                'tipe_id' => 1,
                'kategori_id' => 6,
                'pelapor_id' => 1,
                'waktu' => Carbon::now()->subMinutes(155),
                'lokasi' => 'Edutech Garden FILKOM',
                'kontak' => '081234567892',
                'deskripsi' => 'Novel hilang saat duduk membaca di taman.',
                'foto' => 'https://media.karousell.com/media/photos/products/2025/5/22/buku_novel_looking_for_alaska__1747900347_87575186_progressive_thumbnail.jpg',
                'status_id' => 2,
            ],
            [
                'nama' => 'Buku Tulis Binder',
                'tipe_id' => 1,
                'kategori_id' => 6,
                'pelapor_id' => 1,
                'waktu' => Carbon::now()->subMinutes(65),
                'lokasi' => 'Kelas F4.14 FILKOM',
                'kontak' => '081234567893',
                'deskripsi' => 'Buku tulis binder berisi catatan penting tertinggal di kelas.',
                'foto' => 'https://media.karousell.com/media/photos/products/2025/5/12/buku_tulis_binder_bank_n0bu_1747051779_8792d7b7_progressive_thumbnail.jpg',
                'status_id' => 2,
            ],
            [
                'nama' => 'Pulpen St Dupont',
                'tipe_id' => 1,
                'kategori_id' => 6,
                'pelapor_id' => 1,
                'waktu' => Carbon::now()->subMinutes(210),
                'lokasi' => 'Ruang Dosen FTP',
                'kontak' => '081234567894',
                'deskripsi' => 'Pulpen eksklusif hilang di ruang dosen saat konsultasi.',
                'foto' => 'https://media.karousell.com/media/photos/products/2025/5/10/pulpen_st_dupont_1746867331_5b6357e3_progressive_thumbnail.jpg',
                'status_id' => 2,
            ],
            [
                'nama' => 'Pulpen Montblanc Starwalker Platinum',
                'tipe_id' => 1,
                'kategori_id' => 6,
                'pelapor_id' => 1,
                'waktu' => Carbon::now()->subMinutes(260),
                'lokasi' => 'Ruang Seminar Pascasarjana',
                'kontak' => '081234567895',
                'deskripsi' => 'Pulpen hadiah wisuda hilang setelah seminar.',
                'foto' => 'https://media.karousell.com/media/photos/products/2025/5/13/pulpen_montblanc_starwalker_pl_1747179985_2dbd4af8_progressive_thumbnail.jpg',
                'status_id' => 2,
            ],
            [
                'nama' => 'Kemeja Kotak Oversize',
                'tipe_id' => 1,
                'kategori_id' => 7,
                'pelapor_id' => 1,
                'waktu' => Carbon::now()->subMinutes(80),
                'lokasi' => 'Laundry Express Soekarno Hatta',
                'kontak' => '081234567896',
                'deskripsi' => 'Kemeja hilang saat ambil laundry.',
                'foto' => 'https://media.karousell.com/media/photos/products/2025/5/22/kemeja_kotak_oversize_1747904160_a1e972b1_progressive_thumbnail.jpg',
                'status_id' => 2,
            ],
            [
                'nama' => 'Kemeja Denim',
                'tipe_id' => 1,
                'kategori_id' => 7,
                'pelapor_id' => 1,
                'waktu' => Carbon::now()->subMinutes(150),
                'lokasi' => 'Kantin Fakultas Teknik',
                'kontak' => '081234567897',
                'deskripsi' => 'Kemeja tertinggal di kursi kantin.',
                'foto' => 'https://media.karousell.com/media/photos/products/2025/5/22/kemeja_denim__denim_shirt__kem_1747902016_0b6b7cbf_progressive_thumbnail.jpg',
                'status_id' => 2,
            ],
            [
                'nama' => 'Kaos Anime Yu-Gi-Oh!',
                'tipe_id' => 1,
                'kategori_id' => 7,
                'pelapor_id' => 1,
                'waktu' => Carbon::now()->subMinutes(190),
                'lokasi' => 'Studio Komik UM',
                'kontak' => '081234567898',
                'deskripsi' => 'Kaos kesayangan hilang setelah cosplay event.',
                'foto' => 'https://media.karousell.com/media/photos/products/2025/5/22/kaos_anime_yugioh_sevens_cospa_1747904540_fcd9ad95_progressive_thumbnail.jpg',
                'status_id' => 2,
            ],
            [
                'nama' => 'Kaos Uniqlo Hitam',
                'tipe_id' => 1,
                'kategori_id' => 7,
                'pelapor_id' => 1,
                'waktu' => Carbon::now()->subMinutes(260),
                'lokasi' => 'Masjid Baitul Ilmi',
                'kontak' => '081234567899',
                'deskripsi' => 'Kaos tertinggal di tempat wudhu masjid.',
                'foto' => 'https://media.karousell.com/media/photos/products/2025/5/22/kaos_uniqlo_hitam_1747896497_ee281e67_progressive_thumbnail.jpg',
                'status_id' => 2,
            ],
            [
                'nama' => 'Ripped Boyfriend Jeans',
                'tipe_id' => 1,
                'kategori_id' => 7,
                'pelapor_id' => 1,
                'waktu' => Carbon::now()->subMinutes(290),
                'lokasi' => 'Mall Olympic Garden',
                'kontak' => '081234567800',
                'deskripsi' => 'Celana jeans hilang dari fitting room.',
                'foto' => 'https://media.karousell.com/media/photos/products/2025/5/22/ripped_boyfriend_jeans__celana_1747904033_a314388b_progressive_thumbnail.jpg',
                'status_id' => 2,
            ],
            [
                'nama' => 'Topi Running Nike',
                'tipe_id' => 1,
                'kategori_id' => 7,
                'pelapor_id' => 1,
                'waktu' => Carbon::now()->subMinutes(60),
                'lokasi' => 'Stadion Gajayana',
                'kontak' => '081234567801',
                'deskripsi' => 'Topi tertinggal saat jogging pagi.',
                'foto' => 'https://media.karousell.com/media/photos/products/2025/5/22/topi_running_nike__topi_second_1747903321_c87acdcd_progressive_thumbnail.jpg',
                'status_id' => 2,
            ],
        ]);
    }
}
